// SPDX-License-Identifier: AGPL-3.0-or-later
'use strict'
const test = require('node:test')
const assert = require('node:assert/strict')
const { joinDeadline, joiningAllowed } = require('../src/shoots/ShootService')
const { PermissionFlagsBits: P } = require('discord.js')
const { IDS, fields, fixture, allows } = require('./helpers/shoot')

test('lost channel and announcement responses recover resources without duplicates or repeated pings', async (t) => {
    const f = await fixture(t)
    f.guild.failCreateAfter = true
    const { shoot, id } = await f.create()
    assert.equal(shoot.status, 'provisioning')
    assert.equal(shoot.channel_id, null)
    const created = f.channels.size
    await f.restart()
    f.channels.get(IDS.announce).failSendAfter = true
    await f.service.reconcileAll()
    assert.equal(f.channels.size, created)
    assert.equal((await f.store.getShoot(id, IDS.guild)).announcement_id, null)
    assert.equal(f.channels.get(IDS.announce).sends.length, 1)
    // Expire the nonce so recovery must use the durable marker, not recent-send deduplication.
    for (const message of f.channels.get(IDS.announce).messages.cache.values()) message.nonce = null
    await f.restart()
    await f.service.reconcileAll()
    const recovered = await f.store.getShoot(id, IDS.guild)
    assert.equal(recovered.status, 'open')
    assert.ok(recovered.brief_id && recovered.announcement_id)
    assert.equal(f.channels.get(IDS.announce).sends.length, 1)
    assert.equal(f.channels.get(recovered.channel_id).sends.length, 1)
    assert.ok(f.errors.length >= 2)
})

test('failed close stays durable and retries without exposing inherited category permissions', async (t) => {
    const f = await fixture(t)
    const { shoot } = await f.create()
    const chat = f.channels.get(shoot.channel_id)
    chat.failEdit = true
    await f.service.handleInteraction(f.interaction({ command: 'close', channelId: shoot.channel_id }))
    assert.equal((await f.store.getShoot(shoot.id, IDS.guild)).status, 'closing')
    await f.restart()
    await f.service.reconcileAll()
    assert.equal((await f.store.getShoot(shoot.id, IDS.guild)).status, 'closed')
    assert.equal(chat.parentId, IDS.archive)
    assert.equal(chat.edits.at(-1).lockPermissions, false)
    assert.equal(allows(chat, IDS.invited, P.SendMessages), false)
})

test('deleted briefs recover, announcements remain deleted, and a deleted chat is never recreated', async (t) => {
    const f = await fixture(t)
    let { shoot } = await f.create()
    await f.react(shoot, 'joined')
    const chat = f.channels.get(shoot.channel_id)
    chat.messages.cache.delete(shoot.brief_id)
    f.channels.get(IDS.announce).messages.cache.delete(shoot.announcement_id)
    await f.service.reconcileAll()
    await f.service.reconcileAll()
    const recovered = await f.store.getShoot(shoot.id, IDS.guild)
    assert.notEqual(recovered.brief_id, shoot.brief_id)
    assert.equal(recovered.announcement_id, shoot.announcement_id)
    assert.ok(recovered.announcement_deleted_at)
    assert.equal(f.channels.get(IDS.announce).sends.length, 1)
    assert.ok(allows(chat, IDS.joined, P.ViewChannel))
    assert.deepEqual(f.channels.get(IDS.announce).sends.at(-1).allowedMentions, { parse: [] })
    shoot = recovered
    await f.restart()
    await f.service.reconcileAll()
    assert.equal(f.channels.get(IDS.announce).sends.length, 1)
    assert.ok(allows(chat, IDS.joined, P.ViewChannel))
    f.channels.delete(shoot.channel_id)
    const count = f.channels.size
    await f.service.reconcileAll()
    assert.equal((await f.store.getShoot(shoot.id, IDS.guild)).status, 'missing')
    await f.service.reconcileAll()
    assert.equal(f.channels.size, count)
    assert.ok(f.errors.length)
})

test('editing can extend joining or choose never; reopening and message recovery do not reset the clock', async (t) => {
    const f = await fixture(t)
    let { shoot } = await f.create()
    const start = Date.now() - 36 * 3600000
    await f.store.updateShoot(shoot.id, { join_started_at: start })
    await f.service.reconcileAll()
    let edit = f.interaction({ command: 'edit', channelId: shoot.channel_id })
    await f.service.handleInteraction(edit)
    let submit = f.interaction({ customId: edit.modal.custom_id, channelId: shoot.channel_id })
    submit.fields = fields('Film', '', 'Studio', 'two_days')
    await f.service.handleInteraction(submit)
    shoot = await f.store.getShoot(shoot.id, IDS.guild)
    assert.equal(shoot.join_started_at, start)
    assert.equal(shoot.call_time, null)
    assert.equal(joiningAllowed(shoot), true)
    const currentEdit = f.interaction({ command: 'edit', channelId: shoot.channel_id })
    await f.service.handleInteraction(currentEdit)
    assert.equal(currentEdit.modal.components[4].component.options.find((option) => option.default).value, 'two_days')
    await f.service.handleInteraction(f.interaction({ command: 'close', channelId: shoot.channel_id }))
    await f.service.handleInteraction(f.interaction({ command: 'reopen', channelId: shoot.channel_id }))
    assert.equal((await f.store.getShoot(shoot.id, IDS.guild)).join_started_at, start)
    f.channels.get(IDS.announce).messages.cache.delete(shoot.announcement_id)
    await f.service.reconcileAll()
    assert.equal((await f.store.getShoot(shoot.id, IDS.guild)).join_started_at, start)
    edit = f.interaction({ command: 'edit', channelId: shoot.channel_id })
    await f.service.handleInteraction(edit)
    submit = f.interaction({ customId: edit.modal.custom_id, channelId: shoot.channel_id })
    submit.fields = fields('Film', '', 'Studio', 'never')
    await f.service.handleInteraction(submit)
    assert.equal(joinDeadline(await f.store.getShoot(shoot.id, IDS.guild)), null)
})

test('existing databases migrate with unlimited joining and preserve shoot details and members', async (t) => {
    const f = await fixture(t)
    const { shoot } = await f.create()
    await f.store._exec('DELETE FROM tvm_schema_migrations')
    await f.store._locked(() =>
        f.store._exec('ALTER TABLE shoots DROP COLUMN join_period; ALTER TABLE shoots DROP COLUMN join_started_at;')
    )
    await f.restart()
    const migrated = await f.store.getShoot(shoot.id, IDS.guild)
    assert.equal(migrated.join_period, 'never')
    assert.equal(migrated.join_started_at, null)
    assert.equal(migrated.call_time, shoot.call_time)
    assert.equal(migrated.channel_id, shoot.channel_id)
    assert.ok((await f.store.shootParticipants(shoot.id)).some((row) => row.user_id === IDS.invited && row.invited))
    await f.service.reconcileAll()
    assert.equal(joinDeadline(await f.store.getShoot(shoot.id, IDS.guild)), null)
})

test('reopening before cleanup cancels deletion and a later close starts a fresh 24-hour period', async (t) => {
    const f = await fixture(t)
    const { shoot } = await f.create()
    await f.service.handleInteraction(f.interaction({ command: 'close', channelId: shoot.channel_id }))
    const firstClose = Date.now() - 3600000
    await f.store.updateShoot(shoot.id, { closed_at: firstClose })
    await f.service.handleInteraction(f.interaction({ command: 'close', channelId: shoot.channel_id }))
    assert.equal((await f.store.getShoot(shoot.id, IDS.guild)).closed_at, firstClose)
    await f.service.handleInteraction(f.interaction({ command: 'reopen', channelId: shoot.channel_id }))
    await f.service.reconcileAll()
    assert.equal((await f.store.getShoot(shoot.id, IDS.guild)).closed_at, null)
    assert.equal(f.channels.get(IDS.announce).messages.cache.has(shoot.announcement_id), true)
    await f.service.handleInteraction(f.interaction({ command: 'close', channelId: shoot.channel_id }))
    assert.ok((await f.store.getShoot(shoot.id, IDS.guild)).closed_at > firstClose)
})

test('announcement deletion failures and lost responses retry durably without republishing', async (t) => {
    for (const failure of ['failDelete', 'failDeleteAfter']) {
        const f = await fixture(t)
        const { shoot } = await f.create()
        await f.service.handleInteraction(f.interaction({ command: 'close', channelId: shoot.channel_id }))
        const closedAt = Date.now() - 90000000
        await f.store.updateShoot(shoot.id, { closed_at: closedAt })
        f.channels.get(IDS.announce)[failure] = true
        await f.service.reconcileAll()
        assert.equal((await f.store.getShoot(shoot.id, IDS.guild)).announcement_deleted_at, null)
        assert.equal(f.errors.length, 1)
        await f.restart()
        await f.service.reconcileAll()
        const removed = await f.store.getShoot(shoot.id, IDS.guild)
        assert.ok(removed.announcement_deleted_at)
        assert.equal(removed.closed_at, closedAt)
        assert.equal(f.channels.get(IDS.announce).messages.cache.has(shoot.announcement_id), false)
        assert.equal(f.channels.get(IDS.announce).sends.length, 1)
    }
})

test('closed announcement cleanup still runs if the shoot channel is deleted', async (t) => {
    const f = await fixture(t)
    const { shoot } = await f.create()
    await f.service.handleInteraction(f.interaction({ command: 'close', channelId: shoot.channel_id }))
    f.channels.delete(shoot.channel_id)
    await f.service.reconcileAll()
    assert.equal((await f.store.getShoot(shoot.id, IDS.guild)).status, 'missing')
    await f.store.updateShoot(shoot.id, { closed_at: Date.now() - 90000000 })
    await f.service.reconcileAll()
    assert.ok((await f.store.getShoot(shoot.id, IDS.guild)).announcement_deleted_at)
    assert.equal(f.channels.get(IDS.announce).messages.cache.size, 0)
})

test('older databases add cleanup fields and use the existing closed announcement time', async (t) => {
    const f = await fixture(t)
    const { shoot } = await f.create()
    await f.service.handleInteraction(f.interaction({ command: 'close', channelId: shoot.channel_id }))
    const oldClosedAt = Date.now() - 90000000
    f.channels.get(IDS.announce).messages.cache.get(shoot.announcement_id).editedTimestamp = oldClosedAt
    await f.store._exec('DELETE FROM tvm_schema_migrations')
    await f.store._locked(() =>
        f.store._exec(
            'ALTER TABLE shoots DROP COLUMN closed_at; ALTER TABLE shoots DROP COLUMN announcement_deleted_at; ALTER TABLE shoots DROP COLUMN announcement_republish_pending;'
        )
    )
    await f.restart()
    assert.equal((await f.store.getShoot(shoot.id, IDS.guild)).announcement_deleted_at, null)
    await f.service.reconcileAll()
    const current = await f.store.getShoot(shoot.id, IDS.guild)
    assert.equal(current.closed_at, oldClosedAt)
    assert.ok(current.announcement_deleted_at)
    assert.equal(f.channels.get(IDS.announce).sends.length, 1)
})

test('bot startup can republish deleted announcements while routine reconnect sync cannot', async (t) => {
    const f = await fixture(t)
    const { shoot } = await f.create()
    const channel = f.channels.get(IDS.announce)
    channel.messages.cache.delete(shoot.announcement_id)
    await f.service.reconcileAll()
    await f.service.reconcileAll()
    assert.equal(channel.sends.length, 1)
    await f.restart()
    await f.service.initialize()
    const current = await f.store.getShoot(shoot.id, IDS.guild)
    assert.notEqual(current.announcement_id, shoot.announcement_id)
    assert.equal(current.announcement_deleted_at, null)
    assert.equal(current.join_started_at, shoot.join_started_at)
    assert.equal(channel.sends.length, 2)
    await f.service.reconcileAll()
    assert.equal(channel.sends.length, 2)
    assert.equal(f.errors.length, 0)
})

test('reopening republishes a manually deleted closed announcement without resetting the deadline', async (t) => {
    const f = await fixture(t)
    const { shoot } = await f.create()
    await f.service.handleInteraction(f.interaction({ command: 'close', channelId: shoot.channel_id }))
    const channel = f.channels.get(IDS.announce)
    channel.messages.cache.delete(shoot.announcement_id)
    await f.service.reconcileAll()
    assert.equal(channel.sends.length, 1)
    await f.service.handleInteraction(f.interaction({ command: 'reopen', channelId: shoot.channel_id }))
    const current = await f.store.getShoot(shoot.id, IDS.guild)
    assert.equal(current.status, 'open')
    assert.equal(current.join_started_at, shoot.join_started_at)
    assert.equal(channel.sends.length, 2)
    assert.ok(channel.messages.cache.get(current.announcement_id).reactions.cache.get('🎬').me)
})

test('closed cleanup stays final through edits and startup until explicitly reopened', async (t) => {
    const f = await fixture(t)
    const { shoot } = await f.create()
    await f.service.handleInteraction(f.interaction({ command: 'close', channelId: shoot.channel_id }))
    await f.store.updateShoot(shoot.id, { closed_at: Date.now() - 90000000 })
    await f.service.reconcileAll()
    const edit = f.interaction({ command: 'edit', channelId: shoot.channel_id })
    await f.service.handleInteraction(edit)
    await f.service.handleInteraction(f.interaction({ customId: edit.modal.custom_id, channelId: shoot.channel_id }))
    await f.restart()
    await f.service.initialize()
    assert.equal(f.channels.get(IDS.announce).messages.cache.size, 0)
    assert.equal(f.channels.get(IDS.announce).sends.length, 1)
    assert.equal(f.errors.length, 0)
})

test('important-event publication intent survives a lost send response and routine retry', async (t) => {
    const f = await fixture(t)
    const { shoot } = await f.create()
    const channel = f.channels.get(IDS.announce)
    channel.messages.cache.delete(shoot.announcement_id)
    await f.service.reconcileAll()
    const edit = f.interaction({ command: 'edit', channelId: shoot.channel_id })
    await f.service.handleInteraction(edit)
    channel.failSendAfter = true
    await f.service.handleInteraction(f.interaction({ customId: edit.modal.custom_id, channelId: shoot.channel_id }))
    const pending = await f.store.getShoot(shoot.id, IDS.guild)
    assert.equal(pending.announcement_republish_pending, 1)
    assert.equal(pending.announcement_id, shoot.announcement_id)
    assert.equal(channel.messages.cache.size, 1)
    await f.restart()
    await f.service.reconcileAll()
    const current = await f.store.getShoot(shoot.id, IDS.guild)
    assert.equal(current.announcement_republish_pending, 0)
    assert.equal(current.announcement_deleted_at, null)
    assert.notEqual(current.announcement_id, shoot.announcement_id)
    assert.equal(channel.sends.length, 2)
    assert.deepEqual(channel.sends.at(-1).allowedMentions, { parse: [] })
})

test('a closed announcement with a lost republication response is cleaned up when its original deadline arrives', async (t) => {
    const f = await fixture(t)
    const { shoot } = await f.create()
    const channel = f.channels.get(IDS.announce)
    await f.service.handleInteraction(f.interaction({ command: 'close', channelId: shoot.channel_id }))
    channel.messages.cache.delete(shoot.announcement_id)
    await f.service.reconcileAll()
    const edit = f.interaction({ command: 'edit', channelId: shoot.channel_id })
    await f.service.handleInteraction(edit)
    channel.failSendAfter = true
    await f.service.handleInteraction(f.interaction({ customId: edit.modal.custom_id, channelId: shoot.channel_id }))
    assert.equal(channel.messages.cache.size, 1)
    assert.equal((await f.store.getShoot(shoot.id, IDS.guild)).announcement_republish_pending, 1)
    await f.store.updateShoot(shoot.id, { closed_at: Date.now() - 90000000 })
    await f.restart()
    await f.service.initialize()
    const current = await f.store.getShoot(shoot.id, IDS.guild)
    assert.equal(current.announcement_republish_pending, 0)
    assert.ok(current.announcement_deleted_at)
    assert.equal(channel.messages.cache.size, 0)
    assert.equal(channel.sends.length, 2)
})

test('shutdown during shoot initialization cannot install a reconciliation timer afterward', async (t) => {
    const f = await fixture(t)
    let release
    const waiting = new Promise((resolve) => {
        release = resolve
    })
    const original = f.store.allShoots.bind(f.store)
    f.store.allShoots = async (...args) => {
        await waiting
        return original(...args)
    }
    const initialization = f.service.initialize()
    await new Promise((resolve) => setImmediate(resolve))
    f.service.stop()
    release()
    await initialization
    assert.equal(f.service.timer, undefined)
})
